version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: TaskManagement.Api/Dockerfile
    container_name: taskmanagement-api
    environment:
      # Используем отдельную папку внутри контейнера для файла БД
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/tasks.db
      - ASPNETCORE_ENVIRONMENT=Docker
      - Jwt__SecretKey=super_secret_development_key_change_me_for_docker
      - Jwt__Issuer=TaskManagement.Api
      - Jwt__Audience=TaskManagement.Client
      - Jwt__ExpirationMinutes=120
    volumes:
      - tasks-data:/app/data
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  tasks-data:
    driver: local

